apiRules:
- include:
    uidRegex: ^DevilsHunt
    type: Namespace
- include:
    uidRegex: ^TheInvaders
    type: Namespace
- include:
    uidRegex: ^CardBattle
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace